# Generated by Django 5.0 on 2023-12-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendersName', models.CharField(default='lähettäjän nimi', max_length=50)),
                ('sendersMessage', models.CharField(default='lähettäjän viesti', max_length=1000)),
                ('sendersEmail', models.CharField(default='lähettäjän email', max_length=50)),
                ('sendersPhonenumber', models.IntegerField(default='lähettäjän puh.nro')),
                ('messageForSender', models.CharField(default='', max_length=1000)),
                ('messageForRecipient', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installationName', models.CharField(default='installaation nimi', max_length=50)),
                ('collaboration', models.CharField(default='', max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('media', models.CharField(default='tekniikka', max_length=100)),
                ('imageLink_1', models.CharField(default='', max_length=2090)),
                ('imageLink_2', models.CharField(default='', max_length=2090)),
                ('imageLink_3', models.CharField(default='', max_length=2090)),
                ('imageLink_4', models.CharField(default='', max_length=2090)),
                ('videoLink', models.CharField(default='', max_length=2090)),
                ('instagramLink', models.CharField(default='', max_length=2090)),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='teoksen nimi', max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('media', models.CharField(default='tekniikka', max_length=100)),
                ('imageLink_1', models.CharField(default='kuvalinkki', max_length=2090)),
            ],
        ),
    ]
