# Generated by Django 5.0 on 2023-12-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='messageForRecipient',
        ),
        migrations.AddField(
            model_name='contact',
            name='messageForMe',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sendersEmail',
            field=models.CharField(default='vastaanottajan email', max_length=50),
        ),
    ]
