# Generated by Django 5.0 on 2023-12-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_contact_messageforrecipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messageForMe',
            new_name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='vastaanottajan email', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sendersEmail',
            field=models.CharField(default='lähettäjän email', max_length=50),
        ),
    ]
