# Generated by Django 5.0 on 2023-12-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contact_sendersphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='collaboration',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='imageLink_2',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='imageLink_3',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='imageLink_4',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='instagramLink',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='videoLink',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
    ]
