# Generated by Django 5.0 on 2023-12-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_installation_collaboration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='imageLink_1',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
    ]
