# Generated by Django 5.0 on 2023-12-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_installation_imagelink_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Installation',
        ),
        migrations.AddField(
            model_name='work',
            name='collaboration',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='imageLink_2',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='imageLink_3',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='imageLink_4',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='instagramLink',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='installation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='videoLink',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='imageLink_1',
            field=models.CharField(blank=True, default='', max_length=2090, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='media',
            field=models.CharField(blank=True, default='tekniikka', max_length=100, null=True),
        ),
    ]
